### ISSUE TITLE
Addon doesn't work

### ISSUE THREAD

**Issue by youhitgit** [sshambar/readynas-arm#1]
Hi I successfully installed your addon on my nv+ v2 and rebooted the system.

But I cannot access the shares from my windows 10 laptop.

I tried all sorts of things to fix it but the only way I can access the shares is to disable your addon, reboot and then enable smb1 in windows.

With or without your addon as soon as i disable smb1 in windows i cannot access anything

The addon tells me it installed correctly and when i click on it everything seems ok but i have no access to the shares.

I installed ssh and dug around inside the usr/sbin folder and found that the addon seemed to have changed smbd and nmbd to .orig files and the new ones are linked to usr/local/sbin
And the files smbd and nmbd seem to both be in usr/local/sbin

so it seems the addon done its job but something is wrong ??? 

Do you have any ideas ? Thanks

**Comment by youhitgit** [comment]
If i disable your addon and turn smb off and back on again from the web interface and try to connect to the share using windows then windows pops up and says i cant connect because its smb1.

I then re-enable your addon and windows just says

attempting to connect for ages then says it cant access the share try checking the name or there might be a problem with your network.

(the same happens if i turn smb off and back on from the web interface after enabling your addon) (and the same happens if i restart the whole unit)

If I disable your addon but DO NOT turn smb off and on from the web interface i get the same message saying attempting to connect for ages and then windows can't access, check the spelling etc..

And as i said above if i turn smb off and back on after disabling your addon from the web interface and try connecting again it now says it can't connect because it smb1.

**Comment by sshambar** [comment]
I've released a new addon version: https://github.com/sshambar/readynas-arm/releases/tag/Samba36-3.6.25-2

The new version should fix the samba binary not working after install... please let me know if you still have a problem with the new version, and I'll investigate further :')

**Comment by youhitgit** [comment]
New version works PERFECT. Thank You !
